# Name of your Cloudflare Pages project
name = "social-media-preview-generator"

# Main directory that Cloudflare Pages will deploy
assets = "./public"

# Build command for your project
build.command = "npm install"

# Build output directory
build.output = "public"

# Tell Cloudflare Pages this is a Functions project
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Define environment variables for your Functions
# DO NOT put actual values here, set them in the Cloudflare dashboard
[vars]
# CLOUDFLARE_API_TOKEN = ""
# CLOUDFLARE_ACCOUNT_ID = ""
# GROQ_API_KEY = ""

# Define routes for your Cloudflare Functions
[[routes]]
pattern = "/renderSite"
script = "functions/renderSite.js"

[[routes]]
pattern = "/generateSEO"
script = "functions/generateSEO.js"

[[routes]]
pattern = "/fetchMetadata"
script = "functions/fetchMetadata.js"
