# Cloudflare Pages configuration
name = "cfrest"
compatibility_date = "2023-08-01"

[build]
command = ""
output_dir = "public"

[site]
bucket = "./public"

# Define environment variables for Functions
[vars]
# These should be set in the Cloudflare dashboard
# CLOUDFLARE_API_TOKEN = "your-api-token"
# CLOUDFLARE_ACCOUNT_ID = "your-account-id"
# GROQ_API_KEY = "your-groq-api-key"

# Set up proper binding for Pages Functions
[env.production]
workers_dev = true

# Configure functions directory
[functions]
directory = "functions"
