# Name of your Cloudflare Pages project
name = "social-media-preview-generator"

# Main directory that Cloudflare Pages will deploy
site = { bucket = "./public" }

# Build command for your project
build.command = "npm install"

# Build output directory
build.output_directory = "public"

# Tell Cloudflare Pages this is a Functions project
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Define environment variables for your Functions
# DO NOT put actual values here, set them in the Cloudflare dashboard
[vars]
# CLOUDFLARE_API_TOKEN = ""
# CLOUDFLARE_ACCOUNT_ID = ""
# GROQ_API_KEY = ""

# Configure Cloudflare Pages route handling for production
[routes]
"/" = { type = "file", path = "public/index.html" }
"/renderSite" = { type = "function", function = "renderSite" }
"/fetchMetadata" = { type = "function", function = "fetchMetadata" }
"/generateSEO" = { type = "function", function = "generateSEO" }
"/storeScreenshot" = { type = "function", function = "storeScreenshot" }
"/getScreenshot/*" = { type = "function", function = "getScreenshot" }
